version: '3'
services:
  app:
    image: node:18
    command: sleep infinity
    volumes:
      - ..:/workspace
  postgres:
    image: postgres
    container_name: postgres
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data